/**
 * Serves the FCM service worker at /firebase-messaging-sw.js with the real
 * Firebase config injected from the environment.
 *
 * This replaces the old static public/firebase-messaging-sw.js, which still
 * contained "YOUR_API_KEY" placeholders — meaning push notifications could
 * never work. Generating it here keeps the config in one place (.env.local)
 * instead of hardcoded in a committed file.
 *
 * These NEXT_PUBLIC_* values are not secrets: they are already shipped to
 * every browser inside the client bundle.
 */

export const dynamic = "force-static";

export async function GET() {
  const config = {
    apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
    authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET,
    messagingSenderId: process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    appId: process.env.NEXT_PUBLIC_FIREBASE_APP_ID,
  };

  const body = `// Generated by app/firebase-messaging-sw.js/route.ts — do not edit by hand.
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');

firebase.initializeApp(${JSON.stringify(config, null, 2)});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const notification = payload.notification || {};

  self.registration.showNotification(notification.title || data.title || 'Sri Vinayaka Temple', {
    body: notification.body || data.body || 'New update from the temple.',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    tag: data.announcementId || 'temple-update',
    data: { url: data.url || '/announcements' },
  });
});

// Focus an existing tab if the site is already open, otherwise open one.
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  const target = (event.notification.data && event.notification.data.url) || '/announcements';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clientList) => {
      for (const client of clientList) {
        if ('focus' in client) {
          client.navigate(target);
          return client.focus();
        }
      }
      return self.clients.openWindow(target);
    })
  );
});
`;

  return new Response(body, {
    headers: {
      "Content-Type": "application/javascript; charset=utf-8",
      // Allow the worker to control the whole origin, not just its own folder.
      "Service-Worker-Allowed": "/",
      "Cache-Control": "public, max-age=0, must-revalidate",
    },
  });
}
